spring:
  profiles:
    active: ${ACTIVE_PROFILE:development}
---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:h2:./taskManager
    username: 'sa'
    password:
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true
server:
  port: ${PORT:5000}
---
spring:
  config:
    activate:
      on-profile: production
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  jpa:
    show-sql: false

logging:
  level:
    ROOT: INFO
server:
  error:
    include-stacktrace: never
  port: ${PORT:5000}